# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
favicon: logo.gif

# Personal info
name: Vasant Vohra
title: Software Engineer
email: vasantvohra@gmail.com
phone: +91-8700-410-435
website: ai.vital.in

# Social links

github_username: vasantvohra
linkedin_username: vasantvohra


# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: vasant.jpg
about_content: | # this will include new lines to allow paragraphs
  Software Engineer working on <mark>Artificial Intelligence: Deep Learning technology</mark>.
  Expertise in executing projects across business domains. Also, I have completed a Deep Learning course from **IIT Madras**, NPTEL.
  This course clarified in-depth **mathematics** underlying Deep Learning algorithms. I’m keen to solve challenges by leveraging *AI* technology.
  Since high school, *Python* is my favorite programming language.
  At last, I’m always looking for <mark>full-time opportunities</mark> across the globe. 
  
  ### Skills
  - <b>Experienced</b>
    - <font size = '4'>Programming Language : Python</font>
    - <font size = '4'>Libraries : Keras, OpenCV, PIL, Numpy, Pandas</font>
    - <font size = '4'>Frameworks : TensorFlow, Flask</font>
    - <font size = '4'>Others :  Git</font>
  - <b>Knowledgeable</b>
    - <font size = '4'>Programming Languages : C, Prolog </font>
    - <font size = '4'>Libraries : Sklearn, SpaCy</font>
    - <font size = '4'>Frameworks : Django, Docker, Azure Cognitive Services </font>


# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
more_title: Articles
more_content: | # this will include new lines to allow paragraphs
  I started writing articles on **February 2018** <br>
  - [Metro Rush](https://www.linkedin.com/pulse/metro-rush-vasant-vohra/)
  - [Smart-Meeting Rooms](https://www.linkedin.com/pulse/smart-meeting-rooms-ai-vasant-vohra/)
  - [Connected Automobile](https://www.linkedin.com/pulse/interconnected-world-5g-vasant-vohra/)
# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
